services:
    fastapi-server:
        image: fastapi-server:latest
        env_file:
            - .env
        ports:
            - "8000:8000"
        restart: unless-stopped
        volumes:
            - ./config.json:/app/src/config.json:ro
