services:
    translation-server:
        image: translation-server:latest
        env_file:
            - .env
        ports:
            - "8001:8000"
        restart: unless-stopped
        volumes:
            - ./config.json:/app/src/config.json:ro
